### ISSUE TITLE
Vistas adicionales

### ISSUE THREAD

**Issue by admezalo** [admezalo/GlobHack#14]
Rutas de la app web sin funcionalidad adicional.

[ ] Políticas
[ ] Deportes
[ ] Económicas
[ ] Entretenimiento

**Comment by DanteVDrako** [comment]
-[x] Politica: Vista y ruta diseñada. 
-[x] Economía: Vista y ruta diseñada. 
-[x] Entretenimiento: Vista y ruta diseñada. 
-[x] Cultura: Vista y ruta diseñada. 
-[x] Salud: Vista y ruta diseñada. 
-[x] Deportes: Vista y ruta diseñada.

**Comment by DanteVDrako** [comment]
Realizada.
