### ISSUE TITLE
Vista Principal

### ISSUE THREAD

**Issue by admezalo** [admezalo/GlobHack#7]
Creación de la vista principal del diario digital, que debe tener lo siguiente:
[ ] Barra de navegación.
[ ] Grid de noticias representadas con tarjetas.
[ ] Descripción de cada noticia almacenada local en el proyecto en archivos json (temporal).

**Comment by DanteVDrako** [comment]
- [ X] Barra de navegación: Construida, con enlaces a los diferentes apartados de la pagina.

**Comment by DanteVDrako** [comment]
Realizada.
